export const token = {
  access_token: 'ghu_n49zLaftgj4Nfs5R0jiF0gJH6PdY7v1RVup0',
  expires_in: '28800',
  refresh_token: 'ghr_lwMoKeK6JJlVOOTkEs4ZRa4r3UgjZletB8m4VYCRMgJjhWLMfBL9I6AVrCSbZUjWu8DnJb3m753C',
  refresh_token_expires_in: '15811200',
  scope: '',
  token_type: 'bearer',
};

export const user = {
  login: 'tylerlong',
  id: 733544,
  node_id: 'MDQ6VXNlcjczMzU0NA==',
  avatar_url: 'https://avatars.githubusercontent.com/u/733544?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/tylerlong',
  html_url: 'https://github.com/tylerlong',
  followers_url: 'https://api.github.com/users/tylerlong/followers',
  following_url: 'https://api.github.com/users/tylerlong/following{/other_user}',
  gists_url: 'https://api.github.com/users/tylerlong/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/tylerlong/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/tylerlong/subscriptions',
  organizations_url: 'https://api.github.com/users/tylerlong/orgs',
  repos_url: 'https://api.github.com/users/tylerlong/repos',
  events_url: 'https://api.github.com/users/tylerlong/events{/privacy}',
  received_events_url: 'https://api.github.com/users/tylerlong/received_events',
  type: 'User',
  site_admin: false,
  name: 'Tyler Liu',
  company: 'RingCentral',
  blog: 'https://medium.com/@tylerlong',
  location: 'Belmont, CA, United States',
  email: 'tyler4long@gmail.com',
  hireable: true,
  bio: 'Fullstack developer',
  twitter_username: null,
  public_repos: 608,
  public_gists: 19,
  followers: 374,
  following: 130,
  created_at: '2011-04-16T16:16:17Z',
  updated_at: '2023-10-26T23:00:56Z',
};

export const repos = [
  {
    id: 441286347,
    node_id: 'R_kgDOGk1-yw',
    name: 'fake-update-app',
    full_name: 'tylerlong/fake-update-app',
    private: false,
    owner: {
      login: 'tylerlong',
      id: 733544,
      node_id: 'MDQ6VXNlcjczMzU0NA==',
      avatar_url: 'https://avatars.githubusercontent.com/u/733544?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/tylerlong',
      html_url: 'https://github.com/tylerlong',
      followers_url: 'https://api.github.com/users/tylerlong/followers',
      following_url: 'https://api.github.com/users/tylerlong/following{/other_user}',
      gists_url: 'https://api.github.com/users/tylerlong/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/tylerlong/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/tylerlong/subscriptions',
      organizations_url: 'https://api.github.com/users/tylerlong/orgs',
      repos_url: 'https://api.github.com/users/tylerlong/repos',
      events_url: 'https://api.github.com/users/tylerlong/events{/privacy}',
      received_events_url: 'https://api.github.com/users/tylerlong/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/tylerlong/fake-update-app',
    description: 'Fake Update, display a fake update screen so that you can take a rest.',
    fork: false,
    url: 'https://api.github.com/repos/tylerlong/fake-update-app',
    forks_url: 'https://api.github.com/repos/tylerlong/fake-update-app/forks',
    keys_url: 'https://api.github.com/repos/tylerlong/fake-update-app/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/tylerlong/fake-update-app/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/tylerlong/fake-update-app/teams',
    hooks_url: 'https://api.github.com/repos/tylerlong/fake-update-app/hooks',
    issue_events_url: 'https://api.github.com/repos/tylerlong/fake-update-app/issues/events{/number}',
    events_url: 'https://api.github.com/repos/tylerlong/fake-update-app/events',
    assignees_url: 'https://api.github.com/repos/tylerlong/fake-update-app/assignees{/user}',
    branches_url: 'https://api.github.com/repos/tylerlong/fake-update-app/branches{/branch}',
    tags_url: 'https://api.github.com/repos/tylerlong/fake-update-app/tags',
    blobs_url: 'https://api.github.com/repos/tylerlong/fake-update-app/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/tylerlong/fake-update-app/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/tylerlong/fake-update-app/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/tylerlong/fake-update-app/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/tylerlong/fake-update-app/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/tylerlong/fake-update-app/languages',
    stargazers_url: 'https://api.github.com/repos/tylerlong/fake-update-app/stargazers',
    contributors_url: 'https://api.github.com/repos/tylerlong/fake-update-app/contributors',
    subscribers_url: 'https://api.github.com/repos/tylerlong/fake-update-app/subscribers',
    subscription_url: 'https://api.github.com/repos/tylerlong/fake-update-app/subscription',
    commits_url: 'https://api.github.com/repos/tylerlong/fake-update-app/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/tylerlong/fake-update-app/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/tylerlong/fake-update-app/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/tylerlong/fake-update-app/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/tylerlong/fake-update-app/contents/{+path}',
    compare_url: 'https://api.github.com/repos/tylerlong/fake-update-app/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/tylerlong/fake-update-app/merges',
    archive_url: 'https://api.github.com/repos/tylerlong/fake-update-app/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/tylerlong/fake-update-app/downloads',
    issues_url: 'https://api.github.com/repos/tylerlong/fake-update-app/issues{/number}',
    pulls_url: 'https://api.github.com/repos/tylerlong/fake-update-app/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/tylerlong/fake-update-app/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/tylerlong/fake-update-app/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/tylerlong/fake-update-app/labels{/name}',
    releases_url: 'https://api.github.com/repos/tylerlong/fake-update-app/releases{/id}',
    deployments_url: 'https://api.github.com/repos/tylerlong/fake-update-app/deployments',
    created_at: '2021-12-23T20:15:04Z',
    updated_at: '2021-12-23T20:15:21Z',
    pushed_at: '2021-12-24T04:03:00Z',
    git_url: 'git://github.com/tylerlong/fake-update-app.git',
    ssh_url: 'git@github.com:tylerlong/fake-update-app.git',
    clone_url: 'https://github.com/tylerlong/fake-update-app.git',
    svn_url: 'https://github.com/tylerlong/fake-update-app',
    homepage: null,
    size: 1,
    stargazers_count: 1,
    watchers_count: 1,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: 'main',
    permissions: {
      admin: true,
      maintain: true,
      push: true,
      triage: true,
      pull: true,
    },
  },
];
